global:
  scrape_interval: 4s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
  - job_name: "prometheus" # Name of the job to be displayed in Prometheus
    static_configs:
      - targets: ["node-app:3000"] # Target to scrape metrics from (your Node.js app running on port 3000)
